package com.revature.exception;

public class ExampleClass 
{
    private int value;

    public ExampleClass(int value) {
        this.value = value;
    }

    public void checkValue() throws ThrowCustomException {
        if (value < 0) {
            throw new ThrowCustomException("Value cannot be negative!");
        }
    }

    public static void main(String[] args) {
        try {
            ExampleClass example = new ExampleClass(-1);
            example.checkValue();
        } catch (ThrowCustomException e) {
            System.out.println("Exception caught: " + e.getMessage());
        }
    }
}

